Add debug logging for unrecognized resources in the subsystem archive.
Subsystems will now output a debug logging message when an unrecognized resource is encountered in the subsystem archive. The
level is debug because of the possibility of false positives if the provider knowingly stored resources in the archive that
are neither bundles nor subsystems. The following is an example of what the output might look like.

File "bundle.a.jar" in subsystem with location
"file:/C:/Users/IBM_AD~1/AppData/Local/Temp/paxexam_runner_jwrossjr/application.a.esa" will be ignored because it is not
recognized as a supported resource
org.apache.aries.application.modelling.ModellerException: org.apache.aries.application.modelling.ModellerException:
org.osgi.service.blueprint.container.ComponentDefinitionException: One of ref attribute, bean element, reference element or
ref element must be set
	at
org.apache.aries.application.modelling.impl.ModelledResourceManagerImpl.getServiceElements(ModelledResourceManagerImpl.java:128)
	at
org.apache.aries.application.modelling.impl.ModelledResourceManagerImpl.getServiceElements(ModelledResourceManagerImpl.java:95)
...

git-svn-id: https://svn.apache.org/repos/asf/aries/trunk@1569792 13f79535-47bb-0310-9956-ffa450edef68