[ARIES-2108] Catch NoClassDefFoundError when loading Service-Providers
Fixes https://issues.apache.org/jira/browse/ARIES-2108.

Loading ServiceProvider instances, which depend on classes absent at
runtime (e.g. because they are contained in an optional dependency)
throws a NoClassDefFoundError instead of a ClassNotFoundException,
which is propagated to the caller of
ProviderBundleTrackerCustomizer.addingBundle() and leads to an empty
list of providers.
Instead a NoClassDefFoundError should be handled like a
ClassNotFoundException.

The reason for this different exception in this case is that although
the service class is found it cannot be defined.

The javadoc of 'NoClassDefFoundError' states:
"Thrown if the Java Virtual Machine or a ClassLoader instance tries to
load in the definition of a class (as part of a normal method call or as
part of creating a new instance using the new expression) and no
definition of the class could be found."

The javadoc of 'ClassNotFoundException' states:
"Thrown when an application tries to load in a class through its string
name using:
- The forName method in class Class.
- The findSystemClass method in class ClassLoader .
- The loadClass method in class ClassLoader.
but no definition for the class with the specified name could be found."